### ISSUE TITLE
 An error occurred when verifying security for the message.

### ISSUE THREAD

**Issue by EPIC3D** [joshooaj/EdgeMotionTimeline#3]
Happens when trying to click on a Sequence Definition

TITLE: FillUserControl (Sequence definition)
------------------------------
An error occurred when verifying security for the message.
------------------------------
BUTTONS: OK
------------------------------

2024-08-08 00:18:32.847+02:00 [     8] DEBUG      - Error: StartGetSequences:115 (C:\repos\EdgeMotionTimeline\src\EnhancedTimelinePlugin\Background\EnhancedTimelineSequenceSource.cs) ():Exception thrown: System.AggregateException: One or more errors occurred. ---> System.ServiceModel.FaultException: An error occurred when verifying security for the message.

 --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at EnhancedTimeline.Background.EnhancedTimelineSequenceSource.<>c__DisplayClass25_0.<StartGetSequences>b__0() in C:\repos\EdgeMotionTimeline\src\EnhancedTimelinePlugin\Background\EnhancedTimelineSequenceSource.cs:line 72
---> (Inner Exception #0) System.ServiceModel.FaultException: An error occurred when verifying security for the message.

Milestone 23.3a

**Comment by joshooaj** [comment]
Hi @EPIC3D,

I'm not sure what's happening there but the exception `System.ServiceModel.FaultException` is a low-level error thrown by the WCF/SOAP communication channel the MIP SDK and Management Client are using.

The error `An error occurred when verifying security for the message` suggests to me that the WCF proxy client communicating with the management server failed in some way related to message security/encryption. Maybe the communication channel timed out, or couldn't be setup properly for some reason?

It might be related to some combination of having server encryption enabled and the type of user (Windows or Basic)?

I won't have the time to refactor this module for a week or two at least, but I know there's a lot of room for improvement. When I'm done adding admin-defined browser-based workspaces to the [Web Content Plugin](https://github.com/joshooaj/WebContentPlugin), I may take a look at rebuilding this plugin and following a similar model - open source GPL license with a license requirement on production XProtect systems (free on Essential+ and test licenses).

**Comment by joshooaj** [comment]
Oh hey, this looks similar to the error reported in #2 which was apparently resolved by applying cumulative patches for their version. Cumulative patches for XProtect are all available by version at https://download.milestonesys.com/MTSKB/hotfixes/

**Comment by EPIC3D** [comment]
Oh sorry. Did not see that closed bug report.

Applied latest hotfix: Milestone.Hotfix.202407151821.MC.23.3.96.1.159
Error is gone now. 

Thank you.
